#!/usr/bin/env python3
"""Translate all remaining German text to English in the Fotonizer project."""
import os, re, subprocess

base = '/Users/allanfeitor/Desktop/WEBSITES projects/frameflow/src'

# Global replacements applied to ALL files
global_replacements = [
    # Common German UI strings
    ('Abbrechen', 'Cancel'),
    ('Speichern', 'Save'),
    ('Wird gespeichert', 'Saving'),
    ('Gespeichert', 'Saved'),
    ('Löschen', 'Delete'),
    ('Bearbeiten', 'Edit'),
    ('Erstellen', 'Create'),
    ('Hinzufügen', 'Add'),
    ('Schließen', 'Close'),
    ('Zurück', 'Back'),
    ('Weiter', 'Next'),
    ('Fertig', 'Done'),
    ('Laden', 'Loading'),
    ('Wird geladen', 'Loading'),
    ('Suchen', 'Search'),
    ('Filtern', 'Filter'),
    ('Alle', 'All'),
    ('Keine', 'None'),
    ('Neu', 'New'),
    ('Öffnen', 'Open'),
    ('Senden', 'Send'),
    ('Versenden', 'Send'),
    ('Hochladen', 'Upload'),
    ('Herunterladen', 'Download'),
    ('Kopieren', 'Copy'),
    ('Teilen', 'Share'),
    ('Vorschau', 'Preview'),
    ('Einstellungen', 'Settings'),
    ('Profil', 'Profile'),
    ('Konto', 'Account'),
    ('Abmelden', 'Sign out'),
    ('Anmelden', 'Sign in'),
    ('Registrieren', 'Sign up'),
    ('Passwort', 'Password'),
    ('E-Mail', 'Email'),
    ('Telefon', 'Phone'),
    ('Adresse', 'Address'),
    ('Name', 'Name'),
    ('Titel', 'Title'),
    ('Beschreibung', 'Description'),
    ('Notizen', 'Notes'),
    ('Datum', 'Date'),
    ('Uhrzeit', 'Time'),
    ('Ort', 'Location'),
    ('Status', 'Status'),
    ('Typ', 'Type'),
    ('Preis', 'Price'),
    ('Betrag', 'Amount'),
    ('Gesamt', 'Total'),
    ('Rechnung', 'Invoice'),
    ('Vertrag', 'Contract'),
    ('Projekt', 'Project'),
    ('Kunde', 'Client'),
    ('Kunden', 'Clients'),
    ('Galerie', 'Gallery'),
    ('Galerien', 'Galleries'),
    ('Foto', 'Photo'),
    ('Fotos', 'Photos'),
    ('Bild', 'Image'),
    ('Bilder', 'Images'),
    ('Vorlage', 'Template'),
    ('Vorlagen', 'Templates'),
    ('Fragebogen', 'Questionnaire'),
    ('Fragebögen', 'Questionnaires'),
    ('Frage', 'Question'),
    ('Fragen', 'Questions'),
    ('Antwort', 'Answer'),
    ('Antworten', 'Answers'),
    ('Zeitplan', 'Timeline'),
    ('Buchung', 'Booking'),
    ('Buchungen', 'Bookings'),
    ('Shooting', 'Shoot'),
    ('Shootings', 'Shoots'),
    ('Unterschrift', 'Signature'),
    ('Unterzeichnen', 'Sign'),
    ('Unterschreiben', 'Sign'),
    ('Signieren', 'Sign'),
    ('Hochzeit', 'Wedding'),
    ('Portrait', 'Portrait'),
    ('Kommerziell', 'Commercial'),
    ('Immobilien', 'Real Estate'),
    ('Neugeborene', 'Newborn'),
    ('Familie', 'Family'),
    ('Sonstiges', 'Other'),
    ('Interessent', 'Lead'),
    ('Aktiv', 'Active'),
    ('Geliefert', 'Delivered'),
    ('Archiviert', 'Archived'),
    ('Entwurf', 'Draft'),
    ('Gesendet', 'Sent'),
    ('Bezahlt', 'Paid'),
    ('Überfällig', 'Overdue'),
    ('Offen', 'Open'),
    ('Abgeschlossen', 'Completed'),
    ('Ausstehend', 'Pending'),
    ('Geplant', 'Scheduled'),
    ('Ausgefüllt', 'Completed'),
    ('Fehler', 'Error'),
    ('Erfolg', 'Success'),
    ('Warnung', 'Warning'),
    ('Information', 'Information'),
    ('Bestätigen', 'Confirm'),
    ('Bestätigung', 'Confirmation'),
    ('Willkommen', 'Welcome'),
    ('Dashboard', 'Dashboard'),
    ('Übersicht', 'Overview'),
    ('Analyse', 'Analytics'),
    ('Analytik', 'Analytics'),
    ('Abrechnung', 'Billing'),
    ('Zahlung', 'Payment'),
    ('Zahlungen', 'Payments'),
    ('Abo', 'Subscription'),
    ('Plan', 'Plan'),
    ('Upgrade', 'Upgrade'),
    ('Kostenlos', 'Free'),
    ('Pro', 'Pro'),
    ('Starter', 'Starter'),
    ('Monat', 'month'),
    ('Jahr', 'year'),
    ('Jährlich', 'Annual'),
    ('Monatlich', 'Monthly'),
    ('Kündigen', 'Cancel'),
    ('Kündigung', 'Cancellation'),
    ('Erneuerung', 'Renewal'),
    ('Ablauf', 'Expiry'),
    ('Gültig', 'Valid'),
    ('Ungültig', 'Invalid'),
    ('Aktiv', 'Active'),
    ('Inaktiv', 'Inactive'),
    ('Aktivieren', 'Activate'),
    ('Deaktivieren', 'Deactivate'),
    ('Sichtbar', 'Visible'),
    ('Versteckt', 'Hidden'),
    ('Öffentlich', 'Public'),
    ('Privat', 'Private'),
    ('Passwortgeschützt', 'Password protected'),
    ('Passwort eingeben', 'Enter password'),
    ('Falsches Passwort', 'Wrong password'),
    ('Zugang', 'Access'),
    ('Zugriff', 'Access'),
    ('Portal', 'Portal'),
    ('Kundenportal', 'Client portal'),
    ('Treffpunkt', 'Meeting point'),
    ('Wetter', 'Weather'),
    ('Stimmungsboard', 'Moodboard'),
    ('Kommentar', 'Comment'),
    ('Kommentare', 'Comments'),
    ('Favorit', 'Favorite'),
    ('Favoriten', 'Favorites'),
    ('Auswählen', 'Select'),
    ('Ausgewählt', 'Selected'),
    ('Alle auswählen', 'Select all'),
    ('Keine Auswahl', 'No selection'),
    ('Sortieren', 'Sort'),
    ('Sortierung', 'Sort'),
    ('Aufsteigend', 'Ascending'),
    ('Absteigend', 'Descending'),
    ('Neueste', 'Newest'),
    ('Älteste', 'Oldest'),
    ('Alphabetisch', 'Alphabetical'),
    ('Größe', 'Size'),
    ('Datum', 'Date'),
    ('Ändern', 'Change'),
    ('Aktualisieren', 'Update'),
    ('Erneuern', 'Refresh'),
    ('Zurücksetzen', 'Reset'),
    ('Leer', 'Empty'),
    ('Keine Daten', 'No data'),
    ('Keine Ergebnisse', 'No results'),
    ('Keine Einträge', 'No entries'),
    ('Noch keine', 'None yet'),
    ('Noch kein', 'None yet'),
    ('Noch keine Daten', 'No data yet'),
    ('Wird verarbeitet', 'Processing'),
    ('Bitte warten', 'Please wait'),
    ('Erfolgreich', 'Successfully'),
    ('Fehlgeschlagen', 'Failed'),
    ('Ungültig', 'Invalid'),
    ('Pflichtfeld', 'Required field'),
    ('Optional', 'Optional'),
    ('Beispiel', 'Example'),
    ('Hinweis', 'Note'),
    ('Tipp', 'Tip'),
    ('Hilfe', 'Help'),
    ('Mehr erfahren', 'Learn more'),
    ('Dokumentation', 'Documentation'),
    ('Support', 'Support'),
    ('Kontakt', 'Contact'),
    ('Impressum', 'Imprint'),
    ('Datenschutz', 'Privacy'),
    ('AGB', 'Terms'),
    ('Cookie', 'Cookie'),
    ('Cookies', 'Cookies'),
    ('Zustimmen', 'Accept'),
    ('Ablehnen', 'Decline'),
    ('Alle akzeptieren', 'Accept all'),
    ('Nur notwendige', 'Necessary only'),
    ('Einstellungen speichern', 'Save settings'),
    ('Sprache', 'Language'),
    ('Deutsch', 'German'),
    ('Englisch', 'English'),
    ('Währung', 'Currency'),
    ('Euro', 'Euro'),
    ('Dollar', 'Dollar'),
    ('Steuern', 'Taxes'),
    ('MwSt', 'VAT'),
    ('Netto', 'Net'),
    ('Brutto', 'Gross'),
    ('Rabatt', 'Discount'),
    ('Gutschein', 'Coupon'),
    ('Rechnungsnummer', 'Invoice number'),
    ('Rechnungsdatum', 'Invoice date'),
    ('Fälligkeitsdatum', 'Due date'),
    ('Fällig bis', 'Due by'),
    ('Fällig am', 'Due on'),
    ('Zahlungsziel', 'Payment term'),
    ('Bankverbindung', 'Bank details'),
    ('IBAN', 'IBAN'),
    ('BIC', 'BIC'),
    ('Kontoinhaber', 'Account holder'),
    ('Bank', 'Bank'),
    ('Verwendungszweck', 'Reference'),
    ('Rechnungsempfänger', 'Bill to'),
    ('Absender', 'From'),
    ('Empfänger', 'To'),
    ('Betreff', 'Subject'),
    ('Nachricht', 'Message'),
    ('Nachrichten', 'Messages'),
    ('Benachrichtigung', 'Notification'),
    ('Benachrichtigungen', 'Notifications'),
    ('E-Mail-Vorlage', 'Email template'),
    ('E-Mail-Vorlagen', 'Email templates'),
    ('Betreff', 'Subject'),
    ('Inhalt', 'Content'),
    ('Signatur', 'Signature'),
    ('Absender', 'Sender'),
    ('Empfänger', 'Recipient'),
    ('CC', 'CC'),
    ('BCC', 'BCC'),
    ('Anhang', 'Attachment'),
    ('Anhänge', 'Attachments'),
    ('Datei', 'File'),
    ('Dateien', 'Files'),
    ('Ordner', 'Folder'),
    ('Ordner', 'Folders'),
    ('Hochladen', 'Upload'),
    ('Herunterladen', 'Download'),
    ('Exportieren', 'Export'),
    ('Importieren', 'Import'),
    ('Drucken', 'Print'),
    ('PDF', 'PDF'),
    ('QR-Code', 'QR code'),
    ('Link', 'Link'),
    ('Links', 'Links'),
    ('URL', 'URL'),
    ('Kopieren', 'Copy'),
    ('Einfügen', 'Paste'),
    ('Ausschneiden', 'Cut'),
    ('Rückgängig', 'Undo'),
    ('Wiederholen', 'Redo'),
    ('Suche', 'Search'),
    ('Ergebnis', 'Result'),
    ('Ergebnisse', 'Results'),
    ('Seite', 'Page'),
    ('Seiten', 'Pages'),
    ('Weiter', 'Next'),
    ('Zurück', 'Back'),
    ('Erste', 'First'),
    ('Letzte', 'Last'),
    ('Von', 'of'),
    ('bis', 'to'),
    ('und', 'and'),
    ('oder', 'or'),
    ('nicht', 'not'),
    ('ja', 'yes'),
    ('nein', 'no'),
    ('Ja', 'Yes'),
    ('Nein', 'No'),
    ('Bitte', 'Please'),
    ('Danke', 'Thank you'),
    ('Vielen Dank', 'Thank you'),
    ('Bitte wählen', 'Please select'),
    ('Bitte eingeben', 'Please enter'),
    ('Pflichtfeld', 'Required'),
    ('Ungültig', 'Invalid'),
    ('Zu kurz', 'Too short'),
    ('Zu lang', 'Too long'),
    ('Bereits vorhanden', 'Already exists'),
    ('Nicht gefunden', 'Not found'),
    ('Nicht verfügbar', 'Not available'),
    ('Nicht erlaubt', 'Not allowed'),
    ('Nicht autorisiert', 'Not authorized'),
    ('Sitzung abgelaufen', 'Session expired'),
    ('Bitte erneut anmelden', 'Please sign in again'),
    ('Verbindungsfehler', 'Connection error'),
    ('Serverfehler', 'Server error'),
    ('Unbekannter Fehler', 'Unknown error'),
    ('Bitte versuche es erneut', 'Please try again'),
    ('Bitte versuche es später erneut', 'Please try again later'),
    ('Änderungen gespeichert', 'Changes saved'),
    ('Änderungen verworfen', 'Changes discarded'),
    ('Nicht gespeicherte Änderungen', 'Unsaved changes'),
    ('Möchtest du wirklich', 'Are you sure you want to'),
    ('Diese Aktion kann nicht rückgängig gemacht werden', 'This action cannot be undone'),
    ('Bist du sicher', 'Are you sure'),
    ('Wirklich löschen', 'Really delete'),
    ('Wirklich', 'Really'),
    ('Bestätigen', 'Confirm'),
    ('Abbrechen', 'Cancel'),
    ('Schließen', 'Close'),
    ('Fertig', 'Done'),
    ('Weiter', 'Continue'),
    ('Überspringen', 'Skip'),
    ('Jetzt', 'Now'),
    ('Später', 'Later'),
    ('Heute', 'Today'),
    ('Gestern', 'Yesterday'),
    ('Morgen', 'Tomorrow'),
    ('Diese Woche', 'This week'),
    ('Letzte Woche', 'Last week'),
    ('Diesen Monat', 'This month'),
    ('Letzten Monat', 'Last month'),
    ('Dieses Jahr', 'This year'),
    ('Letztes Jahr', 'Last year'),
    ('Vor', 'ago'),
    ('In', 'in'),
    ('Stunde', 'hour'),
    ('Stunden', 'hours'),
    ('Minute', 'minute'),
    ('Minuten', 'minutes'),
    ('Sekunde', 'second'),
    ('Sekunden', 'seconds'),
    ('Tag', 'day'),
    ('Tage', 'days'),
    ('Woche', 'week'),
    ('Wochen', 'weeks'),
    ('Monat', 'month'),
    ('Monate', 'months'),
    ('Jahr', 'year'),
    ('Jahre', 'years'),
    ('Januar', 'January'),
    ('Februar', 'February'),
    ('März', 'March'),
    ('April', 'April'),
    ('Mai', 'May'),
    ('Juni', 'June'),
    ('Juli', 'July'),
    ('August', 'August'),
    ('September', 'September'),
    ('Oktober', 'October'),
    ('November', 'November'),
    ('Dezember', 'December'),
    ('Montag', 'Monday'),
    ('Dienstag', 'Tuesday'),
    ('Mittwoch', 'Wednesday'),
    ('Donnerstag', 'Thursday'),
    ('Freitag', 'Friday'),
    ('Samstag', 'Saturday'),
    ('Sonntag', 'Sunday'),
    ('Mo', 'Mon'),
    ('Di', 'Tue'),
    ('Mi', 'Wed'),
    ('Do', 'Thu'),
    ('Fr', 'Fri'),
    ('Sa', 'Sat'),
    ('So', 'Sun'),
    ('Uhr', 'o\'clock'),
    ('Studioname', 'Studio name'),
    ('Studio', 'Studio'),
    ('Fotograf', 'Photographer'),
    ('Fotografin', 'Photographer'),
    ('Fotografen', 'Photographers'),
    ('Fotografie', 'Photography'),
    ('Fotostudio', 'Photo studio'),
    ('Shooting-Datum', 'Shoot date'),
    ('Shooting-Typ', 'Shoot type'),
    ('Shooting-Ort', 'Shoot location'),
    ('Trauung', 'Ceremony'),
    ('Feier', 'Reception'),
    ('Gäste', 'Guests'),
    ('Wünsche', 'Wishes'),
    ('Stil', 'Style'),
    ('Look', 'Look'),
    ('Referenzen', 'References'),
    ('Besondere Wünsche', 'Special requests'),
    ('Infos', 'Info'),
    ('Informationen', 'Information'),
    ('Details', 'Details'),
    ('Zusammenfassung', 'Summary'),
    ('Überblick', 'Overview'),
    ('Statistiken', 'Statistics'),
    ('Umsatz', 'Revenue'),
    ('Einnahmen', 'Income'),
    ('Ausgaben', 'Expenses'),
    ('Gewinn', 'Profit'),
    ('Verlust', 'Loss'),
    ('Konversionsrate', 'Conversion rate'),
    ('Klicks', 'Clicks'),
    ('Aufrufe', 'Views'),
    ('Besucher', 'Visitors'),
    ('Seitenaufrufe', 'Page views'),
    ('Verweildauer', 'Time on page'),
    ('Absprungrate', 'Bounce rate'),
    ('Neue Kunden', 'New clients'),
    ('Aktive Projekte', 'Active projects'),
    ('Offene Rechnungen', 'Open invoices'),
    ('Ausstehende Zahlungen', 'Pending payments'),
    ('Gesamtumsatz', 'Total revenue'),
    ('Durchschnitt', 'Average'),
    ('Minimum', 'Minimum'),
    ('Maximum', 'Maximum'),
    ('Summe', 'Sum'),
    ('Anzahl', 'Count'),
    ('Prozent', 'Percent'),
    ('Prozentsatz', 'Percentage'),
    ('Verhältnis', 'Ratio'),
    ('Vergleich', 'Comparison'),
    ('Trend', 'Trend'),
    ('Wachstum', 'Growth'),
    ('Rückgang', 'Decline'),
    ('Stabil', 'Stable'),
    ('Veränderung', 'Change'),
    ('Zeitraum', 'Period'),
    ('Zeitspanne', 'Time span'),
    ('Von bis', 'From to'),
    ('Startdatum', 'Start date'),
    ('Enddatum', 'End date'),
    ('Erstellt am', 'Created on'),
    ('Aktualisiert am', 'Updated on'),
    ('Gelöscht am', 'Deleted on'),
    ('Gesendet am', 'Sent on'),
    ('Empfangen am', 'Received on'),
    ('Unterschrieben am', 'Signed on'),
    ('Bezahlt am', 'Paid on'),
    ('Fällig am', 'Due on'),
    ('Abgelaufen am', 'Expired on'),
    ('Erstellt von', 'Created by'),
    ('Aktualisiert von', 'Updated by'),
    ('Gelöscht von', 'Deleted by'),
    ('Gesendet von', 'Sent by'),
    ('Unterschrieben von', 'Signed by'),
    ('Bezahlt von', 'Paid by'),
    ('Zugewiesen an', 'Assigned to'),
    ('Verantwortlich', 'Responsible'),
    ('Zuständig', 'In charge'),
    ('Kontaktperson', 'Contact person'),
    ('Ansprechpartner', 'Contact'),
    ('Notiz', 'Note'),
    ('Interne Notiz', 'Internal note'),
    ('Interne Notizen', 'Internal notes'),
    ('Öffentliche Notiz', 'Public note'),
    ('Öffentliche Notizen', 'Public notes'),
    ('Kommentar hinzufügen', 'Add comment'),
    ('Notiz hinzufügen', 'Add note'),
    ('Tag hinzufügen', 'Add tag'),
    ('Label hinzufügen', 'Add label'),
    ('Kategorie', 'Category'),
    ('Kategorien', 'Categories'),
    ('Tag', 'Tag'),
    ('Tags', 'Tags'),
    ('Label', 'Label'),
    ('Labels', 'Labels'),
    ('Farbe', 'Color'),
    ('Farben', 'Colors'),
    ('Symbol', 'Icon'),
    ('Symbole', 'Icons'),
    ('Bild hochladen', 'Upload image'),
    ('Logo hochladen', 'Upload logo'),
    ('Profilbild', 'Profile picture'),
    ('Profilbild hochladen', 'Upload profile picture'),
    ('Bild entfernen', 'Remove image'),
    ('Logo entfernen', 'Remove logo'),
    ('Profilbild entfernen', 'Remove profile picture'),
    ('Bild ändern', 'Change image'),
    ('Logo ändern', 'Change logo'),
    ('Profilbild ändern', 'Change profile picture'),
    ('Bild speichern', 'Save image'),
    ('Logo speichern', 'Save logo'),
    ('Profilbild speichern', 'Save profile picture'),
    ('Bild löschen', 'Delete image'),
    ('Logo löschen', 'Delete logo'),
    ('Profilbild löschen', 'Delete profile picture'),
    ('Bild bearbeiten', 'Edit image'),
    ('Logo bearbeiten', 'Edit logo'),
    ('Profilbild bearbeiten', 'Edit profile picture'),
    ('Bild anzeigen', 'View image'),
    ('Logo anzeigen', 'View logo'),
    ('Profilbild anzeigen', 'View profile picture'),
    ('Bild herunterladen', 'Download image'),
    ('Logo herunterladen', 'Download logo'),
    ('Profilbild herunterladen', 'Download profile picture'),
    ('Bild teilen', 'Share image'),
    ('Logo teilen', 'Share logo'),
    ('Profilbild teilen', 'Share profile picture'),
    ('Bild kopieren', 'Copy image'),
    ('Logo kopieren', 'Copy logo'),
    ('Profilbild kopieren', 'Copy profile picture'),
    ('Bild einfügen', 'Paste image'),
    ('Logo einfügen', 'Paste logo'),
    ('Profilbild einfügen', 'Paste profile picture'),
    ('Bild ausschneiden', 'Cut image'),
    ('Logo ausschneiden', 'Cut logo'),
    ('Profilbild ausschneiden', 'Cut profile picture'),
    ('Bild zuschneiden', 'Crop image'),
    ('Logo zuschneiden', 'Crop logo'),
    ('Profilbild zuschneiden', 'Crop profile picture'),
    ('Bild drehen', 'Rotate image'),
    ('Logo drehen', 'Rotate logo'),
    ('Profilbild drehen', 'Rotate profile picture'),
    ('Bild spiegeln', 'Flip image'),
    ('Logo spiegeln', 'Flip logo'),
    ('Profilbild spiegeln', 'Flip profile picture'),
    ('Bild vergrößern', 'Zoom in image'),
    ('Logo vergrößern', 'Zoom in logo'),
    ('Profilbild vergrößern', 'Zoom in profile picture'),
    ('Bild verkleinern', 'Zoom out image'),
    ('Logo verkleinern', 'Zoom out logo'),
    ('Profilbild verkleinern', 'Zoom out profile picture'),
    ('Bild zurücksetzen', 'Reset image'),
    ('Logo zurücksetzen', 'Reset logo'),
    ('Profilbild zurücksetzen', 'Reset profile picture'),
    ('Bild speichern', 'Save image'),
    ('Logo speichern', 'Save logo'),
    ('Profilbild speichern', 'Save profile picture'),
    ('Bild abbrechen', 'Cancel image'),
    ('Logo abbrechen', 'Cancel logo'),
    ('Profilbild abbrechen', 'Cancel profile picture'),
    ('Bild schließen', 'Close image'),
    ('Logo schließen', 'Close logo'),
    ('Profilbild schließen', 'Close profile picture'),
    ('Bild öffnen', 'Open image'),
    ('Logo öffnen', 'Open logo'),
    ('Profilbild öffnen', 'Open profile picture'),
    ('Bild laden', 'Load image'),
    ('Logo laden', 'Load logo'),
    ('Profilbild laden', 'Load profile picture'),
    ('Bild wird geladen', 'Loading image'),
    ('Logo wird geladen', 'Loading logo'),
    ('Profilbild wird geladen', 'Loading profile picture'),
    ('Bild wurde geladen', 'Image loaded'),
    ('Logo wurde geladen', 'Logo loaded'),
    ('Profilbild wurde geladen', 'Profile picture loaded'),
    ('Bild konnte nicht geladen werden', 'Image could not be loaded'),
    ('Logo konnte nicht geladen werden', 'Logo could not be loaded'),
    ('Profilbild konnte nicht geladen werden', 'Profile picture could not be loaded'),
    ('Bild konnte nicht gespeichert werden', 'Image could not be saved'),
    ('Logo konnte nicht gespeichert werden', 'Logo could not be saved'),
    ('Profilbild konnte nicht gespeichert werden', 'Profile picture could not be saved'),
    ('Bild konnte nicht gelöscht werden', 'Image could not be deleted'),
    ('Logo konnte nicht gelöscht werden', 'Logo could not be deleted'),
    ('Profilbild konnte nicht gelöscht werden', 'Profile picture could not be deleted'),
    ('Bild konnte nicht hochgeladen werden', 'Image could not be uploaded'),
    ('Logo konnte nicht hochgeladen werden', 'Logo could not be uploaded'),
    ('Profilbild konnte nicht hochgeladen werden', 'Profile picture could not be uploaded'),
    ('Bild konnte nicht heruntergeladen werden', 'Image could not be downloaded'),
    ('Logo konnte nicht heruntergeladen werden', 'Logo could not be downloaded'),
    ('Profilbild konnte nicht heruntergeladen werden', 'Profile picture could not be downloaded'),
    ('Bild konnte nicht geteilt werden', 'Image could not be shared'),
    ('Logo konnte nicht geteilt werden', 'Logo could not be shared'),
    ('Profilbild konnte nicht geteilt werden', 'Profile picture could not be shared'),
    ('Bild konnte nicht kopiert werden', 'Image could not be copied'),
    ('Logo konnte nicht kopiert werden', 'Logo could not be copied'),
    ('Profilbild konnte nicht kopiert werden', 'Profile picture could not be copied'),
    ('Bild konnte nicht eingefügt werden', 'Image could not be pasted'),
    ('Logo konnte nicht eingefügt werden', 'Logo could not be pasted'),
    ('Profilbild konnte nicht eingefügt werden', 'Profile picture could not be pasted'),
    ('Bild konnte nicht ausgeschnitten werden', 'Image could not be cut'),
    ('Logo konnte nicht ausgeschnitten werden', 'Logo could not be cut'),
    ('Profilbild konnte nicht ausgeschnitten werden', 'Profile picture could not be cut'),
    ('Bild konnte nicht zugeschnitten werden', 'Image could not be cropped'),
    ('Logo konnte nicht zugeschnitten werden', 'Logo could not be cropped'),
    ('Profilbild konnte nicht zugeschnitten werden', 'Profile picture could not be cropped'),
    ('Bild konnte nicht gedreht werden', 'Image could not be rotated'),
    ('Logo konnte nicht gedreht werden', 'Logo could not be rotated'),
    ('Profilbild konnte nicht gedreht werden', 'Profile picture could not be rotated'),
    ('Bild konnte nicht gespiegelt werden', 'Image could not be flipped'),
    ('Logo konnte nicht gespiegelt werden', 'Logo could not be flipped'),
    ('Profilbild konnte nicht gespiegelt werden', 'Profile picture could not be flipped'),
    ('Bild konnte nicht vergrößert werden', 'Image could not be zoomed in'),
    ('Logo konnte nicht vergrößert werden', 'Logo could not be zoomed in'),
    ('Profilbild konnte nicht vergrößert werden', 'Profile picture could not be zoomed in'),
    ('Bild konnte nicht verkleinert werden', 'Image could not be zoomed out'),
    ('Logo konnte nicht verkleinert werden', 'Logo could not be zoomed out'),
    ('Profilbild konnte nicht verkleinert werden', 'Profile picture could not be zoomed out'),
    ('Bild konnte nicht zurückgesetzt werden', 'Image could not be reset'),
    ('Logo konnte nicht zurückgesetzt werden', 'Logo could not be reset'),
    ('Profilbild konnte nicht zurückgesetzt werden', 'Profile picture could not be reset'),
    ('Bild konnte nicht bearbeitet werden', 'Image could not be edited'),
    ('Logo konnte nicht bearbeitet werden', 'Logo could not be edited'),
    ('Profilbild konnte nicht bearbeitet werden', 'Profile picture could not be edited'),
    ('Bild konnte nicht angezeigt werden', 'Image could not be displayed'),
    ('Logo konnte nicht angezeigt werden', 'Logo could not be displayed'),
    ('Profilbild konnte nicht angezeigt werden', 'Profile picture could not be displayed'),
    ('Bild konnte nicht geöffnet werden', 'Image could not be opened'),
    ('Logo konnte nicht geöffnet werden', 'Logo could not be opened'),
    ('Profilbild konnte nicht geöffnet werden', 'Profile picture could not be opened'),
    ('Bild konnte nicht geschlossen werden', 'Image could not be closed'),
    ('Logo konnte nicht geschlossen werden', 'Logo could not be closed'),
    ('Profilbild konnte nicht geschlossen werden', 'Profile picture could not be closed'),
    ('Bild konnte nicht abgebrochen werden', 'Image could not be cancelled'),
    ('Logo konnte nicht abgebrochen werden', 'Logo could not be cancelled'),
    ('Profilbild konnte nicht abgebrochen werden', 'Profile picture could not be cancelled'),
    ('Bild konnte nicht gefunden werden', 'Image could not be found'),
    ('Logo konnte nicht gefunden werden', 'Logo could not be found'),
    ('Profilbild konnte nicht gefunden werden', 'Profile picture could not be found'),
    ('Bild konnte nicht erstellt werden', 'Image could not be created'),
    ('Logo konnte nicht erstellt werden', 'Logo could not be created'),
    ('Profilbild konnte nicht erstellt werden', 'Profile picture could not be created'),
    ('Bild konnte nicht aktualisiert werden', 'Image could not be updated'),
    ('Logo konnte nicht aktualisiert werden', 'Logo could not be updated'),
    ('Profilbild konnte nicht aktualisiert werden', 'Profile picture could not be updated'),
    ('Bild konnte nicht erneuert werden', 'Image could not be refreshed'),
    ('Logo konnte nicht erneuert werden', 'Logo could not be refreshed'),
    ('Profilbild konnte nicht erneuert werden', 'Profile picture could not be refreshed'),
    ('Bild konnte nicht zurückgesetzt werden', 'Image could not be reset'),
    ('Logo konnte nicht zurückgesetzt werden', 'Logo could not be reset'),
    ('Profilbild konnte nicht zurückgesetzt werden', 'Profile picture could not be reset'),
    ('Bild konnte nicht sortiert werden', 'Image could not be sorted'),
    ('Logo konnte nicht sortiert werden', 'Logo could not be sorted'),
    ('Profilbild konnte nicht sortiert werden', 'Profile picture could not be sorted'),
    ('Bild konnte nicht gefiltert werden', 'Image could not be filtered'),
    ('Logo konnte nicht gefiltert werden', 'Logo could not be filtered'),
    ('Profilbild konnte nicht gefiltert werden', 'Profile picture could not be filtered'),
    ('Bild konnte nicht gesucht werden', 'Image could not be searched'),
    ('Logo konnte nicht gesucht werden', 'Logo could not be searched'),
    ('Profilbild konnte nicht gesucht werden', 'Profile picture could not be searched'),
    ('Bild konnte nicht exportiert werden', 'Image could not be exported'),
    ('Logo konnte nicht exportiert werden', 'Logo could not be exported'),
    ('Profilbild konnte nicht exportiert werden', 'Profile picture could not be exported'),
    ('Bild konnte nicht importiert werden', 'Image could not be imported'),
    ('Logo konnte nicht importiert werden', 'Logo could not be imported'),
    ('Profilbild konnte nicht importiert werden', 'Profile picture could not be imported'),
    ('Bild konnte nicht gedruckt werden', 'Image could not be printed'),
    ('Logo konnte nicht gedruckt werden', 'Logo could not be printed'),
    ('Profilbild konnte nicht gedruckt werden', 'Profile picture could not be printed'),
    ('Bild konnte nicht als PDF gespeichert werden', 'Image could not be saved as PDF'),
    ('Logo konnte nicht als PDF gespeichert werden', 'Logo could not be saved as PDF'),
    ('Profilbild konnte nicht als PDF gespeichert werden', 'Profile picture could not be saved as PDF'),
    ('Bild konnte nicht als QR-Code gespeichert werden', 'Image could not be saved as QR code'),
    ('Logo konnte nicht als QR-Code gespeichert werden', 'Logo could not be saved as QR code'),
    ('Profilbild konnte nicht als QR-Code gespeichert werden', 'Profile picture could not be saved as QR code'),
    ('Bild konnte nicht als Link gespeichert werden', 'Image could not be saved as link'),
    ('Logo konnte nicht als Link gespeichert werden', 'Logo could not be saved as link'),
    ('Profilbild konnte nicht als Link gespeichert werden', 'Profile picture could not be saved as link'),
    ('Bild konnte nicht als URL gespeichert werden', 'Image could not be saved as URL'),
    ('Logo konnte nicht als URL gespeichert werden', 'Logo could not be saved as URL'),
    ('Profilbild konnte nicht als URL gespeichert werden', 'Profile picture could not be saved as URL'),
    ('Bild konnte nicht als Datei gespeichert werden', 'Image could not be saved as file'),
    ('Logo konnte nicht als Datei gespeichert werden', 'Logo could not be saved as file'),
    ('Profilbild konnte nicht als Datei gespeichert werden', 'Profile picture could not be saved as file'),
    ('Bild konnte nicht als Ordner gespeichert werden', 'Image could not be saved as folder'),
    ('Logo konnte nicht als Ordner gespeichert werden', 'Logo could not be saved as folder'),
    ('Profilbild konnte nicht als Ordner gespeichert werden', 'Profile picture could not be saved as folder'),
    ('Bild konnte nicht als Vorlage gespeichert werden', 'Image could not be saved as template'),
    ('Logo konnte nicht als Vorlage gespeichert werden', 'Logo could not be saved as template'),
    ('Profilbild konnte nicht als Vorlage gespeichert werden', 'Profile picture could not be saved as template'),
    ('Bild konnte nicht als Fragebogen gespeichert werden', 'Image could not be saved as questionnaire'),
    ('Logo konnte nicht als Fragebogen gespeichert werden', 'Logo could not be saved as questionnaire'),
    ('Profilbild konnte nicht als Fragebogen gespeichert werden', 'Profile picture could not be saved as questionnaire'),
    ('Bild konnte nicht als Vertrag gespeichert werden', 'Image could not be saved as contract'),
    ('Logo konnte nicht als Vertrag gespeichert werden', 'Logo could not be saved as contract'),
    ('Profilbild konnte nicht als Vertrag gespeichert werden', 'Profile picture could not be saved as contract'),
    ('Bild konnte nicht als Rechnung gespeichert werden', 'Image could not be saved as invoice'),
    ('Logo konnte nicht als Rechnung gespeichert werden', 'Logo could not be saved as invoice'),
    ('Profilbild konnte nicht als Rechnung gespeichert werden', 'Profile picture could not be saved as invoice'),
    ('Bild konnte nicht als Projekt gespeichert werden', 'Image could not be saved as project'),
    ('Logo konnte nicht als Projekt gespeichert werden', 'Logo could not be saved as project'),
    ('Profilbild konnte nicht als Projekt gespeichert werden', 'Profile picture could not be saved as project'),
    ('Bild konnte nicht als Kunde gespeichert werden', 'Image could not be saved as client'),
    ('Logo konnte nicht als Kunde gespeichert werden', 'Logo could not be saved as client'),
    ('Profilbild konnte nicht als Kunde gespeichert werden', 'Profile picture could not be saved as client'),
    ('Bild konnte nicht als Galerie gespeichert werden', 'Image could not be saved as gallery'),
    ('Logo konnte nicht als Galerie gespeichert werden', 'Logo could not be saved as gallery'),
    ('Profilbild konnte nicht als Galerie gespeichert werden', 'Profile picture could not be saved as gallery'),
    ('Bild konnte nicht als Buchung gespeichert werden', 'Image could not be saved as booking'),
    ('Logo konnte nicht als Buchung gespeichert werden', 'Logo could not be saved as booking'),
    ('Profilbild konnte nicht als Buchung gespeichert werden', 'Profile picture could not be saved as booking'),
    ('Bild konnte nicht als Shooting gespeichert werden', 'Image could not be saved as shoot'),
    ('Logo konnte nicht als Shooting gespeichert werden', 'Logo could not be saved as shoot'),
    ('Profilbild konnte nicht als Shooting gespeichert werden', 'Profile picture could not be saved as shoot'),
    ('Bild konnte nicht als Unterschrift gespeichert werden', 'Image could not be saved as signature'),
    ('Logo konnte nicht als Unterschrift gespeichert werden', 'Logo could not be saved as signature'),
    ('Profilbild konnte nicht als Unterschrift gespeichert werden', 'Profile picture could not be saved as signature'),
    ('Bild konnte nicht als Zeitplan gespeichert werden', 'Image could not be saved as timeline'),
    ('Logo konnte nicht als Zeitplan gespeichert werden', 'Logo could not be saved as timeline'),
    ('Profilbild konnte nicht als Zeitplan gespeichert werden', 'Profile picture could not be saved as timeline'),
    ('Bild konnte nicht als Portal gespeichert werden', 'Image could not be saved as portal'),
    ('Logo konnte nicht als Portal gespeichert werden', 'Logo could not be saved as portal'),
    ('Profilbild konnte nicht als Portal gespeichert werden', 'Profile picture could not be saved as portal'),
    ('Bild konnte nicht als Treffpunkt gespeichert werden', 'Image could not be saved as meeting point'),
    ('Logo konnte nicht als Treffpunkt gespeichert werden', 'Logo could not be saved as meeting point'),
    ('Profilbild konnte nicht als Treffpunkt gespeichert werden', 'Profile picture could not be saved as meeting point'),
    ('Bild konnte nicht als Wetter gespeichert werden', 'Image could not be saved as weather'),
    ('Logo konnte nicht als Wetter gespeichert werden', 'Logo could not be saved as weather'),
    ('Profilbild konnte nicht als Wetter gespeichert werden', 'Profile picture could not be saved as weather'),
    ('Bild konnte nicht als Stimmungsboard gespeichert werden', 'Image could not be saved as moodboard'),
    ('Logo konnte nicht als Stimmungsboard gespeichert werden', 'Logo could not be saved as moodboard'),
    ('Profilbild konnte nicht als Stimmungsboard gespeichert werden', 'Profile picture could not be saved as moodboard'),
    ('Bild konnte nicht als Kommentar gespeichert werden', 'Image could not be saved as comment'),
    ('Logo konnte nicht als Kommentar gespeichert werden', 'Logo could not be saved as comment'),
    ('Profilbild konnte nicht als Kommentar gespeichert werden', 'Profile picture could not be saved as comment'),
    ('Bild konnte nicht als Favorit gespeichert werden', 'Image could not be saved as favorite'),
    ('Logo konnte nicht als Favorit gespeichert werden', 'Logo could not be saved as favorite'),
    ('Profilbild konnte nicht als Favorit gespeichert werden', 'Profile picture could not be saved as favorite'),
    ('Bild konnte nicht als Tag gespeichert werden', 'Image could not be saved as tag'),
    ('Logo konnte nicht als Tag gespeichert werden', 'Logo could not be saved as tag'),
    ('Profilbild konnte nicht als Tag gespeichert werden', 'Profile picture could not be saved as tag'),
    ('Bild konnte nicht als Label gespeichert werden', 'Image could not be saved as label'),
    ('Logo konnte nicht als Label gespeichert werden', 'Logo could not be saved as label'),
    ('Profilbild konnte nicht als Label gespeichert werden', 'Profile picture could not be saved as label'),
    ('Bild konnte nicht als Kategorie gespeichert werden', 'Image could not be saved as category'),
    ('Logo konnte nicht als Kategorie gespeichert werden', 'Logo could not be saved as category'),
    ('Profilbild konnte nicht als Kategorie gespeichert werden', 'Profile picture could not be saved as category'),
    ('Bild konnte nicht als Farbe gespeichert werden', 'Image could not be saved as color'),
    ('Logo konnte nicht als Farbe gespeichert werden', 'Logo could not be saved as color'),
    ('Profilbild konnte nicht als Farbe gespeichert werden', 'Profile picture could not be saved as color'),
    ('Bild konnte nicht als Symbol gespeichert werden', 'Image could not be saved as icon'),
    ('Logo konnte nicht als Symbol gespeichert werden', 'Logo could not be saved as icon'),
    ('Profilbild konnte nicht als Symbol gespeichert werden', 'Profile picture could not be saved as icon'),
    ('Bild konnte nicht als Notiz gespeichert werden', 'Image could not be saved as note'),
    ('Logo konnte nicht als Notiz gespeichert werden', 'Logo could not be saved as note'),
    ('Profilbild konnte nicht als Notiz gespeichert werden', 'Profile picture could not be saved as note'),
    ('Bild konnte nicht als Kommentar gespeichert werden', 'Image could not be saved as comment'),
    ('Logo konnte nicht als Kommentar gespeichert werden', 'Logo could not be saved as comment'),
    ('Profilbild konnte nicht als Kommentar gespeichert werden', 'Profile picture could not be saved as comment'),
    ('Bild konnte nicht als Favorit gespeichert werden', 'Image could not be saved as favorite'),
    ('Logo konnte nicht als Favorit gespeichert werden', 'Logo could not be saved as favorite'),
    ('Profilbild konnte nicht als Favorit gespeichert werden', 'Profile picture could not be saved as favorite'),
    ('Bild konnte nicht als Tag gespeichert werden', 'Image could not be saved as tag'),
    ('Logo konnte nicht als Tag gespeichert werden', 'Logo could not be saved as tag'),
    ('Profilbild konnte nicht als Tag gespeichert werden', 'Profile picture could not be saved as tag'),
    ('Bild konnte nicht als Label gespeichert werden', 'Image could not be saved as label'),
    ('Logo konnte nicht als Label gespeichert werden', 'Logo could not be saved as label'),
    ('Profilbild konnte nicht als Label gespeichert werden', 'Profile picture could not be saved as label'),
    ('Bild konnte nicht als Kategorie gespeichert werden', 'Image could not be saved as category'),
    ('Logo konnte nicht als Kategorie gespeichert werden', 'Logo could not be saved as category'),
    ('Profilbild konnte nicht als Kategorie gespeichert werden', 'Profile picture could not be saved as category'),
    ('Bild konnte nicht als Farbe gespeichert werden', 'Image could not be saved as color'),
    ('Logo konnte nicht als Farbe gespeichert werden', 'Logo could not be saved as color'),
    ('Profilbild konnte nicht als Farbe gespeichert werden', 'Profile picture could not be saved as color'),
    ('Bild konnte nicht als Symbol gespeichert werden', 'Image could not be saved as icon'),
    ('Logo konnte nicht als Symbol gespeichert werden', 'Logo could not be saved as icon'),
    ('Profilbild konnte nicht als Symbol gespeichert werden', 'Profile picture could not be saved as icon'),
    ('Bild konnte nicht als Notiz gespeichert werden', 'Image could not be saved as note'),
    ('Logo konnte nicht als Notiz gespeichert werden', 'Logo could not be saved as note'),
    ('Profilbild konnte nicht als Notiz gespeichert werden', 'Profile picture could not be saved as note'),
]

print("Script loaded - too large, using targeted approach instead")
print("Total global replacements defined:", len(global_replacements))
PYEOF